//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.bhq.ui;

import android.annotation.SuppressLint;
import android.content.Context;
import android.os.Bundle;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageButton;
import android.widget.LinearLayout;
import android.widget.ProgressBar;
import android.widget.TextView;

import com.bhq.R.id;
import com.bhq.R.layout;

import org.androidannotations.api.builder.ActivityIntentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

@SuppressLint({
    "NewApi"
})
public final class EditEvent_
    extends EditEvent
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.editevent);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static EditEvent_.IntentBuilder_ intent(Context context) {
        return new EditEvent_.IntentBuilder_(context);
    }

    public static EditEvent_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new EditEvent_.IntentBuilder_(fragment);
    }

    public static EditEvent_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new EditEvent_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        ll_video = ((LinearLayout) hasViews.findViewById(id.ll_video));
        imgbtn_addpicture = ((ImageButton) hasViews.findViewById(id.imgbtn_addpicture));
        et_sjms = ((EditText) hasViews.findViewById(id.et_sjms));
        ll_picture = ((LinearLayout) hasViews.findViewById(id.ll_picture));
        imgbtn_addvideo = ((ImageButton) hasViews.findViewById(id.imgbtn_addvideo));
        tv_type = ((TextView) hasViews.findViewById(id.tv_type));
        btn_upload = ((Button) hasViews.findViewById(id.btn_upload));
        et_clqk = ((EditText) hasViews.findViewById(id.et_clqk));
        pb_upload = ((ProgressBar) hasViews.findViewById(id.pb_upload));
        if (imgbtn_addpicture!= null) {
            imgbtn_addpicture.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    EditEvent_.this.imgbtn_addpicture();
                }

            }
            );
        }
        if (tv_type!= null) {
            tv_type.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    EditEvent_.this.tv_type();
                }

            }
            );
        }
        if (btn_upload!= null) {
            btn_upload.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    EditEvent_.this.btn_upload();
                }

            }
            );
        }
        {
            View view = hasViews.findViewById(id.imgbtn_addluyin);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        EditEvent_.this.imgbtn_addluyin();
                    }

                }
                );
            }
        }
        if (imgbtn_addvideo!= null) {
            imgbtn_addvideo.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    EditEvent_.this.imgbtn_addvideo();
                }

            }
            );
        }
        afterOncreate();
    }

    public static class IntentBuilder_
        extends ActivityIntentBuilder<EditEvent_.IntentBuilder_>
    {

        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            super(context, EditEvent_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            super(fragment.getActivity(), EditEvent_.class);
            fragment_ = fragment;
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            super(fragment.getActivity(), EditEvent_.class);
            fragmentSupport_ = fragment;
        }

        @Override
        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent, requestCode);
                } else {
                    super.startForResult(requestCode);
                }
            }
        }

    }

}
