//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.bhq.ui;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import android.widget.ImageButton;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;

import org.androidannotations.api.builder.FragmentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class Offline_MainFragment_
    extends com.bhq.ui.Offline_MainFragment
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private View contentView_;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    @Override
    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        return contentView_;
    }

    @Override
    public void onDestroyView() {
        contentView_ = null;
        super.onDestroyView();
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static Offline_MainFragment_.FragmentBuilder_ builder() {
        return new Offline_MainFragment_.FragmentBuilder_();
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        btn_account = ((ImageButton) hasViews.findViewById(com.bhq.R.id.btn_account));
        container_map = ((FrameLayout) hasViews.findViewById(com.bhq.R.id.container_map));
        ll_task = ((LinearLayout) hasViews.findViewById(com.bhq.R.id.ll_task));
        ll_find = ((LinearLayout) hasViews.findViewById(com.bhq.R.id.ll_find));
        titlebar_home = ((RelativeLayout) hasViews.findViewById(com.bhq.R.id.titlebar_home));
        ll_eventhappen = ((LinearLayout) hasViews.findViewById(com.bhq.R.id.ll_eventhappen));
        if (btn_account!= null) {
            btn_account.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    Offline_MainFragment_.this.btn_account();
                }

            }
            );
        }
        if (ll_eventhappen!= null) {
            ll_eventhappen.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    Offline_MainFragment_.this.ll_eventhappen();
                }

            }
            );
        }
        if (ll_task!= null) {
            ll_task.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    Offline_MainFragment_.this.ll_task();
                }

            }
            );
        }
        if (ll_find!= null) {
            ll_find.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    Offline_MainFragment_.this.ll_find();
                }

            }
            );
        }
        afterOncreate();
    }

    public static class FragmentBuilder_
        extends FragmentBuilder<Offline_MainFragment_.FragmentBuilder_, com.bhq.ui.Offline_MainFragment>
    {


        @Override
        public com.bhq.ui.Offline_MainFragment build() {
            Offline_MainFragment_ fragment_ = new Offline_MainFragment_();
            fragment_.setArguments(args);
            return fragment_;
        }

    }

}
