//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.bhq.ui;

import android.annotation.SuppressLint;
import android.content.Context;
import android.os.Bundle;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageButton;
import android.widget.LinearLayout;
import android.widget.ProgressBar;
import android.widget.TextView;

import com.bhq.R.id;
import com.bhq.R.layout;

import org.androidannotations.api.builder.ActivityIntentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

@SuppressLint({
    "NewApi"
})
public final class Offline_AddCJXX_
    extends Offline_AddCJXX
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.adddiscovery);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static Offline_AddCJXX_.IntentBuilder_ intent(Context context) {
        return new Offline_AddCJXX_.IntentBuilder_(context);
    }

    public static Offline_AddCJXX_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new Offline_AddCJXX_.IntentBuilder_(fragment);
    }

    public static Offline_AddCJXX_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new Offline_AddCJXX_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        ll_wsw_picture = ((LinearLayout) hasViews.findViewById(id.ll_wsw_picture));
        imgbtn_animal_addJYpicture = ((ImageButton) hasViews.findViewById(id.imgbtn_animal_addJYpicture));
        imgbtn_animal_addFBpicture = ((ImageButton) hasViews.findViewById(id.imgbtn_animal_addFBpicture));
        ll_animal_FBpicture = ((LinearLayout) hasViews.findViewById(id.ll_animal_FBpicture));
        imgbtn_addfruitpicture = ((ImageButton) hasViews.findViewById(id.imgbtn_addfruitpicture));
        et_ke = ((EditText) hasViews.findViewById(id.et_ke));
        et_tz = ((EditText) hasViews.findViewById(id.et_tz));
        et_mu = ((EditText) hasViews.findViewById(id.et_mu));
        et_gang = ((EditText) hasViews.findViewById(id.et_gang));
        ll_animal_wholepicture = ((LinearLayout) hasViews.findViewById(id.ll_animal_wholepicture));
        imgbtn_addLeafpicture = ((ImageButton) hasViews.findViewById(id.imgbtn_addLeafpicture));
        tv_type = ((TextView) hasViews.findViewById(id.tv_type));
        ll_flowerpicture = ((LinearLayout) hasViews.findViewById(id.ll_flowerpicture));
        et_bwys = ((EditText) hasViews.findViewById(id.et_bwys));
        tv_bwd = ((TextView) hasViews.findViewById(id.tv_bwd));
        btn_upload = ((Button) hasViews.findViewById(id.btn_upload));
        et_xx = ((EditText) hasViews.findViewById(id.et_xx));
        et_zm = ((EditText) hasViews.findViewById(id.et_zm));
        pb_upload = ((ProgressBar) hasViews.findViewById(id.pb_upload));
        tv_bhjb = ((TextView) hasViews.findViewById(id.tv_bhjb));
        imgbtn_addwholepicture = ((ImageButton) hasViews.findViewById(id.imgbtn_addwholepicture));
        imgbtn_animal_addwholepicture = ((ImageButton) hasViews.findViewById(id.imgbtn_animal_addwholepicture));
        tv_title = ((TextView) hasViews.findViewById(id.tv_title));
        imgbtn_wsw_addpicture = ((ImageButton) hasViews.findViewById(id.imgbtn_wsw_addpicture));
        ll_wholepicture = ((LinearLayout) hasViews.findViewById(id.ll_wholepicture));
        ll_addanimalpicture = ((LinearLayout) hasViews.findViewById(id.ll_addanimalpicture));
        ll_addwswpicture = ((LinearLayout) hasViews.findViewById(id.ll_addwswpicture));
        ll_animal_JYpicture = ((LinearLayout) hasViews.findViewById(id.ll_animal_JYpicture));
        et_szhj = ((EditText) hasViews.findViewById(id.et_szhj));
        et_bz = ((EditText) hasViews.findViewById(id.et_bz));
        ll_addplantpicture = ((LinearLayout) hasViews.findViewById(id.ll_addplantpicture));
        ll_fruitpicture = ((LinearLayout) hasViews.findViewById(id.ll_fruitpicture));
        ll_Leafpicture = ((LinearLayout) hasViews.findViewById(id.ll_Leafpicture));
        imgbtn_addflowerpicture = ((ImageButton) hasViews.findViewById(id.imgbtn_addflowerpicture));
        if (tv_bhjb!= null) {
            tv_bhjb.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    Offline_AddCJXX_.this.tv_bhjb();
                }

            }
            );
        }
        if (imgbtn_addLeafpicture!= null) {
            imgbtn_addLeafpicture.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    Offline_AddCJXX_.this.imgbtn_addLeafpicture();
                }

            }
            );
        }
        if (tv_bwd!= null) {
            tv_bwd.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    Offline_AddCJXX_.this.tv_bwd();
                }

            }
            );
        }
        if (imgbtn_addfruitpicture!= null) {
            imgbtn_addfruitpicture.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    Offline_AddCJXX_.this.imgbtn_addfruitpicture();
                }

            }
            );
        }
        if (imgbtn_animal_addwholepicture!= null) {
            imgbtn_animal_addwholepicture.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    Offline_AddCJXX_.this.imgbtn_animal_addwholepicture();
                }

            }
            );
        }
        {
            View view = hasViews.findViewById(id.imgbtn_back);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        Offline_AddCJXX_.this.imgbtn_back();
                    }

                }
                );
            }
        }
        if (tv_type!= null) {
            tv_type.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    Offline_AddCJXX_.this.tv_type();
                }

            }
            );
        }
        if (imgbtn_animal_addFBpicture!= null) {
            imgbtn_animal_addFBpicture.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    Offline_AddCJXX_.this.imgbtn_animal_addFBpicture();
                }

            }
            );
        }
        if (imgbtn_animal_addJYpicture!= null) {
            imgbtn_animal_addJYpicture.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    Offline_AddCJXX_.this.imgbtn_animal_addJYpicture();
                }

            }
            );
        }
        if (imgbtn_addwholepicture!= null) {
            imgbtn_addwholepicture.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    Offline_AddCJXX_.this.imgbtn_addwholepicture();
                }

            }
            );
        }
        if (btn_upload!= null) {
            btn_upload.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    Offline_AddCJXX_.this.btn_upload();
                }

            }
            );
        }
        if (imgbtn_addflowerpicture!= null) {
            imgbtn_addflowerpicture.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    Offline_AddCJXX_.this.imgbtn_addflowerpicture();
                }

            }
            );
        }
        if (imgbtn_wsw_addpicture!= null) {
            imgbtn_wsw_addpicture.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    Offline_AddCJXX_.this.imgbtn_wsw_addpicture();
                }

            }
            );
        }
        afterOncreate();
    }

    public static class IntentBuilder_
        extends ActivityIntentBuilder<Offline_AddCJXX_.IntentBuilder_>
    {

        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            super(context, Offline_AddCJXX_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            super(fragment.getActivity(), Offline_AddCJXX_.class);
            fragment_ = fragment;
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            super(fragment.getActivity(), Offline_AddCJXX_.class);
            fragmentSupport_ = fragment;
        }

        @Override
        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent, requestCode);
                } else {
                    super.startForResult(requestCode);
                }
            }
        }

    }

}
