//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.bhq.ui;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import android.widget.TextView;

import com.bhq.widget.CircleImageView;

import org.androidannotations.api.builder.FragmentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class Offline_IServiceFragment_
    extends com.bhq.ui.Offline_IServiceFragment
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private View contentView_;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    @Override
    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        return contentView_;
    }

    @Override
    public void onDestroyView() {
        contentView_ = null;
        super.onDestroyView();
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static Offline_IServiceFragment_.FragmentBuilder_ builder() {
        return new Offline_IServiceFragment_.FragmentBuilder_();
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        tv_changepwd = ((TextView) hasViews.findViewById(com.bhq.R.id.tv_changepwd));
        circle_img = ((CircleImageView) hasViews.findViewById(com.bhq.R.id.circle_img));
        tv_phone = ((TextView) hasViews.findViewById(com.bhq.R.id.tv_phone));
        tv_name = ((TextView) hasViews.findViewById(com.bhq.R.id.tv_name));
        fl_new = ((FrameLayout) hasViews.findViewById(com.bhq.R.id.fl_new));
        tv_renewversion = ((TextView) hasViews.findViewById(com.bhq.R.id.tv_renewversion));
        {
            View view = hasViews.findViewById(com.bhq.R.id.rl_bz);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        Offline_IServiceFragment_.this.rl_bz();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(com.bhq.R.id.rl_exist);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        Offline_IServiceFragment_.this.rl_exist();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(com.bhq.R.id.rl_gy);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        Offline_IServiceFragment_.this.rl_gy();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(com.bhq.R.id.rl_changeppdw);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        Offline_IServiceFragment_.this.rl_changeppdw();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(com.bhq.R.id.rl_gx);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        Offline_IServiceFragment_.this.rl_gx();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(com.bhq.R.id.rl_tb);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        Offline_IServiceFragment_.this.rl_tb();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(com.bhq.R.id.rl_yj);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        Offline_IServiceFragment_.this.rl_yj();
                    }

                }
                );
            }
        }
        afterOncreate();
    }

    public static class FragmentBuilder_
        extends FragmentBuilder<Offline_IServiceFragment_.FragmentBuilder_, com.bhq.ui.Offline_IServiceFragment>
    {


        @Override
        public com.bhq.ui.Offline_IServiceFragment build() {
            Offline_IServiceFragment_ fragment_ = new Offline_IServiceFragment_();
            fragment_.setArguments(args);
            return fragment_;
        }

    }

}
