//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.bhq.ui;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ImageButton;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.TextView;

import com.tencent.tencentmap.mapsdk.map.MapView;

import org.androidannotations.api.builder.FragmentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class PatrolControlFragment_
    extends com.bhq.ui.PatrolControlFragment
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private View contentView_;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    @Override
    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        return contentView_;
    }

    @Override
    public void onDestroyView() {
        contentView_ = null;
        super.onDestroyView();
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static PatrolControlFragment_.FragmentBuilder_ builder() {
        return new PatrolControlFragment_.FragmentBuilder_();
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        tv_gps = ((TextView) hasViews.findViewById(com.bhq.R.id.tv_gps));
        btn_complete = ((Button) hasViews.findViewById(com.bhq.R.id.btn_complete));
        mapview = ((MapView) hasViews.findViewById(com.bhq.R.id.mapview));
        tv_starttime = ((TextView) hasViews.findViewById(com.bhq.R.id.tv_starttime));
        tv_runtime = ((TextView) hasViews.findViewById(com.bhq.R.id.tv_runtime));
        rl_mapmore = ((RelativeLayout) hasViews.findViewById(com.bhq.R.id.rl_mapmore));
        btn_runcontrol = ((Button) hasViews.findViewById(com.bhq.R.id.btn_runcontrol));
        btn_continue = ((Button) hasViews.findViewById(com.bhq.R.id.btn_continue));
        tv_runlength = ((TextView) hasViews.findViewById(com.bhq.R.id.tv_runlength));
        imgbtn_home = ((ImageButton) hasViews.findViewById(com.bhq.R.id.imgbtn_home));
        ll_pb_gps = ((LinearLayout) hasViews.findViewById(com.bhq.R.id.ll_pb_gps));
        ll_GPS = ((LinearLayout) hasViews.findViewById(com.bhq.R.id.ll_GPS));
        btn_location = ((Button) hasViews.findViewById(com.bhq.R.id.btn_location));
        if (btn_continue!= null) {
            btn_continue.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    PatrolControlFragment_.this.btn_continue();
                }

            }
            );
        }
        if (btn_location!= null) {
            btn_location.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    PatrolControlFragment_.this.btn_location();
                }

            }
            );
        }
        if (btn_complete!= null) {
            btn_complete.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    PatrolControlFragment_.this.btn_complete();
                }

            }
            );
        }
        if (btn_runcontrol!= null) {
            btn_runcontrol.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    PatrolControlFragment_.this.btn_runcontrol();
                }

            }
            );
        }
        afterOncreate();
    }

    public static class FragmentBuilder_
        extends FragmentBuilder<PatrolControlFragment_.FragmentBuilder_, com.bhq.ui.PatrolControlFragment>
    {


        @Override
        public com.bhq.ui.PatrolControlFragment build() {
            PatrolControlFragment_ fragment_ = new PatrolControlFragment_();
            fragment_.setArguments(args);
            return fragment_;
        }

    }

}
