//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.bhq.ui;

import android.annotation.SuppressLint;
import android.content.Context;
import android.os.Bundle;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.Button;
import android.widget.FrameLayout;
import android.widget.ImageButton;
import android.widget.TextView;

import com.bhq.R.id;
import com.bhq.R.layout;

import org.androidannotations.api.builder.ActivityIntentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

@SuppressLint({
    "NewApi"
})
public final class ShowPest_
    extends ShowPest
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.showpest);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static ShowPest_.IntentBuilder_ intent(Context context) {
        return new ShowPest_.IntentBuilder_(context);
    }

    public static ShowPest_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new ShowPest_.IntentBuilder_(fragment);
    }

    public static ShowPest_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new ShowPest_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        tv_number = ((TextView) hasViews.findViewById(id.tv_number));
        imgbtn_back = ((ImageButton) hasViews.findViewById(id.imgbtn_back));
        btn_foundation = ((Button) hasViews.findViewById(id.btn_foundation));
        img_container = ((FrameLayout) hasViews.findViewById(id.img_container));
        contain_more = ((FrameLayout) hasViews.findViewById(id.contain_more));
        btn_record = ((Button) hasViews.findViewById(id.btn_record));
        fl_contain = ((FrameLayout) hasViews.findViewById(id.fl_contain));
        tv_name = ((TextView) hasViews.findViewById(id.tv_name));
        btn_video = ((Button) hasViews.findViewById(id.btn_video));
        btn_other = ((Button) hasViews.findViewById(id.btn_other));
        if (btn_record!= null) {
            btn_record.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    ShowPest_.this.btn_record();
                }

            }
            );
        }
        if (btn_other!= null) {
            btn_other.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    ShowPest_.this.btn_other();
                }

            }
            );
        }
        if (btn_video!= null) {
            btn_video.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    ShowPest_.this.btn_video();
                }

            }
            );
        }
        if (btn_foundation!= null) {
            btn_foundation.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    ShowPest_.this.btn_foundation();
                }

            }
            );
        }
        if (imgbtn_back!= null) {
            imgbtn_back.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    ShowPest_.this.imgbtn_back();
                }

            }
            );
        }
        afterOncreate();
    }

    public static class IntentBuilder_
        extends ActivityIntentBuilder<ShowPest_.IntentBuilder_>
    {

        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            super(context, ShowPest_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            super(fragment.getActivity(), ShowPest_.class);
            fragment_ = fragment;
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            super(fragment.getActivity(), ShowPest_.class);
            fragmentSupport_ = fragment;
        }

        @Override
        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent, requestCode);
                } else {
                    super.startForResult(requestCode);
                }
            }
        }

    }

}
