//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.bhq.ui;

import android.content.Context;
import android.os.Bundle;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.TextView;

import com.bhq.R.id;
import com.bhq.R.layout;

import org.androidannotations.api.builder.ActivityIntentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class TaskContent_
    extends TaskContent
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.taskcontent);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static TaskContent_.IntentBuilder_ intent(Context context) {
        return new TaskContent_.IntentBuilder_(context);
    }

    public static TaskContent_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new TaskContent_.IntentBuilder_(fragment);
    }

    public static TaskContent_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new TaskContent_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        tv_ywcry = ((TextView) hasViews.findViewById(id.tv_ywcry));
        btn_wc = ((Button) hasViews.findViewById(id.btn_wc));
        btn_check_yqsq = ((Button) hasViews.findViewById(id.btn_check_yqsq));
        tv_WRJZSJ = ((TextView) hasViews.findViewById(id.tv_WRJZSJ));
        tv_WRTXSJ = ((TextView) hasViews.findViewById(id.tv_WRTXSJ));
        tv_RWMC = ((TextView) hasViews.findViewById(id.tv_RWMC));
        tv_ZCRXM = ((TextView) hasViews.findViewById(id.tv_ZCRXM));
        btn_sqyq_bpq = ((Button) hasViews.findViewById(id.btn_sqyq_bpq));
        tv_RWMS = ((TextView) hasViews.findViewById(id.tv_RWMS));
        tv_WRKSSJ = ((TextView) hasViews.findViewById(id.tv_WRKSSJ));
        tv_CYR = ((TextView) hasViews.findViewById(id.tv_CYR));
        ll_CYR = ((LinearLayout) hasViews.findViewById(id.ll_CYR));
        tv_ZYD = ((TextView) hasViews.findViewById(id.tv_ZYD));
        {
            View view = hasViews.findViewById(id.imgbtn_back);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        TaskContent_.this.imgbtn_back();
                    }

                }
                );
            }
        }
        if (btn_wc!= null) {
            btn_wc.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    TaskContent_.this.btn_wc();
                }

            }
            );
        }
        afterOncreate();
    }

    public static class IntentBuilder_
        extends ActivityIntentBuilder<TaskContent_.IntentBuilder_>
    {

        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            super(context, TaskContent_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            super(fragment.getActivity(), TaskContent_.class);
            fragment_ = fragment;
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            super(fragment.getActivity(), TaskContent_.class);
            fragmentSupport_ = fragment;
        }

        @Override
        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent, requestCode);
                } else {
                    super.startForResult(requestCode);
                }
            }
        }

    }

}
